### ISSUE TITLE
Hash introduction premature

### ISSUE THREAD

**Issue by sammarcus** [learn-co-curriculum/collections_practice_vol_2#1]
I looked over earlier content and didn't see any mention or explanation of a hash, a student said they were confused because it hadn't been explained earlier. Hash is the very next lesson, so not sure if it was premature or intentional to be here.

**Comment by SophieDeBenedetto** [comment]
agreed, this should be move to next unit.

**Comment by AnnJohn** [comment]
Iceboxing for now and should be addressed later

**Comment by AnnJohn** [comment]
Moved this lab to the Hashes section
