### ISSUE TITLE
Possible issue with difficulty of lab?

### ISSUE THREAD

**Issue by salomekbg** [learn-co-curriculum/collections_practice_vol_2#12]
When I start the lab in Learn IDE, I get the following:
![image](https://cloud.githubusercontent.com/assets/18332476/15622531/9622575c-2437-11e6-9d1d-6a2c294cf513.png)

I've been doing the lessons in order, so I'm not sure if this lab is out of order?  Also, it covers methods using hashes, but we haven't been introduced to them as yet.  I checked the order of the lessons and we cover hashes right after this lab.  I'm not sure if the point here is to complete our own research?

Or are we supposed to have access to Collections_Practice_vol_1 instead of this and vol_2 was supposed to come later on?

**Comment by sgharms** [comment]
Hi there, @salomekbg 

You're right! This material didn't belong here! We've removed it and hopefully removed the confusion.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
