### ISSUE TITLE
"Bonus - Collections Practice 2" should come later in the track, after "Intro to Hashes"

### ISSUE THREAD

**Issue by ethanryan** [learn-co-curriculum/collections_practice_vol_2#13]
"Bonus - Collections Practice 2" is now the last lesson in the Enumerables section, but it should be in the "More on Hashes" section, after "Bonus: Collections Practice".

For example: "Bonus - Collections Practice 2" contains a method, #merge_data, that asks Learn students to combine two nested data structures into one, but this problem is coming before students have been introduced to hashes or nested data structures.

**Comment by pigusan** [comment]
agreed^

**Comment by sgharms** [comment]
Hi there, @ethanryan and @bmcilhenny 

You're right! This material didn't belong here! We've removed it and hopefully removed the confusion.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙

**Comment by Dwake5** [comment]
This issue has not been fixed. This lab which seems to requires hash's come before anything about hash's.
