### ISSUE TITLE
Associated with the Collections Practice (vol. 1) lab

### ISSUE THREAD

**Issue by szrharrison** [learn-co-curriculum/collections_practice_vol_2#14]
#1 Issues
 * Inconsistencies with naming
 * "Collections Practices" out of order
 * Unable to access "Collections Practice" (vol 1)
### Inconsistencies with naming
These two labs styled in two different ways as can be seen in the following image:
 * Bonus: Collections Practice
 * Bonus - Collections Practice 2
![image](https://cloud.githubusercontent.com/assets/18292880/23775427/9d9b95de-04f6-11e7-9de0-87e9c56a059e.png)
### "Collections Practices" out of order
I'm unsure whether these are ordered as intended but, as you can see in the previous image, students will arrive at "Collections Practice 2" before doing "Collections Practice". Furthermore, "Collections Practice 2", which deals with manipulating hashes, appears under the "Enumerables" lesson, before students are exposed to hashes.
### Unable to access "Collections Practice" (vol 1)
The links at the top of the page for "Collections Practice" (vol 1) link to "Collections Practice 2" (see image for verification):
![image](https://cloud.githubusercontent.com/assets/18292880/23775277/e313cc2c-04f5-11e7-8e97-0c247768ce00.png)

**Comment by sgharms** [comment]
Hiya @szrharrison,

Thank you for spotting this complex and confusing issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙

**Comment by noobboon7** [comment]
hello, 
this issue is still a thing...

**Comment by sgharms** [comment]
@noobboon7 Could you please open a new issue on this and provide more information? There are two issues at play in this one and I'm not sure which part you're encountering.
