### ISSUE TITLE
Possibly wrong placement in curriculum order

### ISSUE THREAD

**Issue by walkingalchemy** [learn-co-curriculum/collections_practice_vol_2#15]
This is great stuff for practice but the second half (4-8) of the methods require knowledge of Hashes and this lesson is showing up before the Intro to Hashes section.

**Comment by jenncacace** [comment]
I agree this should be split 1-4 should be Collections Practice 1.

5-8 should be Collections Practice 2 - i'm not sure why it's broken out this way.

**Comment by sgharms** [comment]
Hi there, @walkingalchemy 

You're right! This material didn't belong here! We've removed it and hopefully removed the confusion.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
