### ISSUE TITLE
This lab is in the wrong category 

### ISSUE THREAD

**Issue by gveve** [learn-co-curriculum/collections_practice_vol_2#16]
This lab comes too soon, and also is at the end of the  "more on hashes"  section. 

it is also exactly the same as "bonus collections practice" which is previous to it in the "more on hashes section"

**Comment by GuttermanA** [comment]
Seconded

**Comment by jenncacace** [comment]
I agree!

**Comment by sgharms** [comment]
Hi there, multiple people!

You're right! This material didn't belong here! We've removed it and hopefully removed the confusion.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
