### ISSUE TITLE
This Lab expects it's students to know about hashes when they shouldn't yet

### ISSUE THREAD

**Issue by alec-horwitz** [learn-co-curriculum/collections_practice_vol_2#18]
This lab expects students to have an decent grasp on hashes right before they are introduced to them. Unless students are expected to skip it and come back to it, this lab should be moved to after they learn about hashes. There are other more overcome-able issues with the pre-work that are very similar to this one in which students might not be able to figure out without a pre-exsiting background in CS.

**Comment by sgharms** [comment]
Hey @alec-horwitz, closing this duplicate. Thanks again.
