### ISSUE TITLE
Bug: Duplicate lab with questions to advanced to be this early in the pre-work!

### ISSUE THREAD

**Issue by alec-horwitz** [learn-co-curriculum/collections_practice_vol_2#19]
This lab appears to be at the end of the "Enumerables" section of the pre-work by mistake. This mistake is evident for Three reasons:

1) If you look at the name of this lab it's "Collections Practice Vol 2". There was never a volume 1 so how could there be a volume 2.

2) If you get to the end of the lab chances are you will be asked to do things that you were never tought but are now expected to be well versed in (namely working with hashes).

3) There is a duplicate of this lab at the end of the "More on Hashes" section with the same name and same questions.

**Comment by sgharms** [comment]
Hi there, @alec-horwitz!

You're right! This material didn't belong here! We've removed it and hopefully removed the confusion.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
