### ISSUE TITLE
Seems like we need a proper README here

### ISSUE THREAD

**Issue by DakotaLMartinez** [learn-co-curriculum/collections_practice_vol_2#21]
All solutions should be generic and work for any "case" is hard to flush out when we don't know what other cases would be. It might make this much more clear if we had a couple example inputs for each of the methods.

**Comment by maxwellbenton** [comment]
Hey @DakotaLMartinez,

Thanks for this feedback! I've updated this lesson's readme to include additional instructions for each method expected, along with example code snippets for each to hopefully make things clearer for students. We're also in the process of revamping the Ruby / module 1 content so this will likely be moved and updated again in the near future.

Hope all is well!
