### ISSUE TITLE
Remove lab from this section as Hashes have not been introduced yet

### ISSUE THREAD

**Issue by JessRudder** [learn-co-curriculum/collections_practice_vol_2#3]
I recommend removing this lab from this part of the public tracks.

This lab appears to require knowledge of hashes which are not introduced until the next section.

Stretch labs like this can make sense as part of the 12-week immersive curriculum for students that are a bit further ahead than other students; however, in a 'work-at-your-own-pace' home-based curriculum, it is confusing.  Students think they should be able to do it just with what they've learned to that point.

Recommend moving it to the end of the hashes section or at least adding a note that they may not be able to complete it without learning about hashes first.

**Comment by AnnJohn** [comment]
Issue #4 raises the same thing. Iceboxing for now.

**Comment by sammarcus** [comment]
@JessRudder ditto, see https://github.com/learn-co-curriculum/collections_practice_vol_2/issues/1 :blush:

**Comment by sammarcus** [comment]
@JessRudder ditto, see https://github.com/learn-co-curriculum/collections_practice_vol_2/issues/1 :blush:

**Comment by JessRudder** [comment]
@sammarcus Haha....looks like there are multiple issues about this.  Next time I'll remember Rule No. 1 of opening an issue - make sure the same issue hasn't already been opened yet. :)

**Comment by AnnJohn** [comment]
Similar issue in #5

**Comment by AnnJohn** [comment]
Also similar issue in #2

**Comment by AnnJohn** [comment]
Moved this lab to the Hashes section.
