### ISSUE TITLE
location of this lesson

### ISSUE THREAD

**Issue by dougtebay** [learn-co-curriculum/collections_practice_vol_2#5]
I would suggest moving this lesson to a later point in the syllabus. Most of the problems require an understanding of hashes, which haven't been covered yet.

**Comment by AnnJohn** [comment]
@dougtebay thanks for raising the issue. Since it's an issue that's been raised already, please make sure to check other open, existing issues and you can comment  in that issue. Closing this one.

**Comment by dougtebay** [comment]
Got it, thanks!
