### ISSUE TITLE
Relocate this lab?

### ISSUE THREAD

**Issue by pedrotp** [learn-co-curriculum/collections_practice_vol_2#6]
This lab uses hash manipulation, nesting, etc but a student going through the curriculum hasn't even learned what a hash *is* yet at this point. I'd suggest moving this toward the end of the "Intro to Hashes" section.

**Comment by AnnJohn** [comment]
@pedrotp Thanks for raising the issue. Yes, we're aware of this and will be moving around and changing the pre-work curriculum. Thanks again

**Comment by AnnJohn** [comment]
Moved this lab to the Hashes section
